### ISSUE TITLE
Invalid SSL certificate

### ISSUE THREAD

**Issue by san650** [halfdan/embadge.io#11]
When trying to load the badge.svg image, I get an error page. The request is blocked by Chrome due to an invalid (expired?) SSL certificate.

![screen shot 2016-09-11 at 9 40 05 pm](https://cloud.githubusercontent.com/assets/1234607/18421782/65b4f0e0-7868-11e6-8f6c-75a8fd8bd215.png)

Thanks for working and hosting this service, I find it really useful.

**Comment by halfdan** [comment]
@san650 Thanks for reporting this - just updated the cert. Sorry about this.
