### ISSUE TITLE
Badges are black in Safari

### ISSUE THREAD

**Issue by amk221** [halfdan/embadge.io#3]
<img width="894" alt="screen shot 2016-02-08 at 23 52 49" src="https://cloud.githubusercontent.com/assets/382061/12903384/36ec8b0e-cebf-11e5-99fe-e9f654d0157a.png">

**Comment by mmun** [comment]
The SVG validator is [giving an error](https://validator.w3.org/check?uri=http%3A%2F%2Fembadge.io%2Fb%2F1.svg&charset=%28detect+automatically%29&doctype=Inline&group=0) on the badge file. I'm looking into it...
